Updated

diff --git a/python-hello_world/0-run b/python-hello_world/0-run
--- a/python-hello_world/0-run
+++ b/python-hello_world/0-run
@@ -1,3 +1,8 @@
 #!/bin/bash
-/usr/bin/python $PYFILE
-python main.py
+
+if [ -z "$PYFILE" ]; then
+  echo "Error: PYFILE environment variable is not set."
+  exit 1
+fi
+
+python3 "$PYFILE"
